export default {
    //上海期货交易所价格查询
    shfutures:{
        type:'品种代号',
        typename:'品种名称',
        price:'最新价',
        changequantity:'涨跌量',
        buyprice:'买入价',
        buyamount:'买入量',
        sellprice:'卖出价',
        sellamount:'卖出量',
        tradeamount:'总成交量',
        openingprice:'开盘价',
        lastclosingprice:'昨收盘价',
        maxprice:'最高价',
        minprice:'最低价',
        holdamount:'持仓量',
        increaseamount:'增仓'
    },
    //银行账户黄金价格查询
    bank:{
        type:'品种代号',
        midprice:'中间价',
        buyprice:'买入价',
        sellprice:'卖出价',
        maxprice:'最高价',
        minprice:'最低价',
        openingprice:'开盘价',
        lastclosingprice:'昨收盘价',
        changequantity:'涨跌量',
        updatetime:'更新时间'
    },
    //香港金银业贸易场价格查询
    hkgold:{
        type:'品种代号',
        buyprice:'买入价',
        sellprice:'卖出价',
        finalprice:'成交价',
        // openingprice:'开盘价',
        // closingprice:'收市价',
        maxprice:'最高价',
        minprice:'最低价',
        updatetime:'更新时间'
    },
    //货币贵金属价格查询
    currency:{
        type:'品种代号',
        price:'最新价',
        changequantity:'涨跌量',
        dollarrate:'兑美元汇率',
        ratechange:'汇率变动',
        updatetime:'更新时间'
    },
    //伦敦金银价格查询
    london:{
        type:'品种代号',
        price:'最新价',
        changepercent:'涨跌幅',
        changequantity:'涨跌量',
        openingprice:'开盘价',
        maxprice:'最高价',
        minprice:'最低价',
        lastclosingprice:'昨收盘价',
        amplitude:'振幅',
        buyprice:'买入价',
        sellprice:'卖出价',
        updatetime:'更新时间'
    },
    //上海黄金交易所价格查询
    shgold:{
        type:'品种代号',
        typename:'品种名称',
        price:'最新价',
        openingprice:'开盘价',
        maxprice:'最高价',
        minprice:'最低价',
        changepercent:'涨跌幅',
        lastclosingprice:'昨收盘价',
        tradeamount:'总成交量',
        updatetime:'更新时间'
    }
}